Insert into categories(categoryname) values ('Art');
Insert into categories(categoryname) values ('Design');
Insert into categories(categoryname) values ('Events');
Insert into categories(categoryname) values ('Fashion');
Insert into categories(categoryname) values ('Health');
Insert into categories(categoryname) values ('Marketing');
Insert into categories(categoryname) values ('Mobile application');
Insert into categories(categoryname) values ('Music');
Insert into categories(categoryname) values ('Photography');
Insert into categories(categoryname) values ('Services');
Insert into categories(categoryname) values ('Technology');
Insert into categories(categoryname) values ('Web');