Insert into projects(projectname, projectdescription, projectamounttoraise, projectamountraised, projectcreationdate, projectclosingdate, projectimage1, projectimage2, projectimage3, projectimage4, fkuserid, fkcategoryid, nbshareordinary, nbsharepreferencial, nbsharenonvoting, nbshareredeemable, "validatedProject") VALUES
    ('Services nunc sed id semper risus in. Tortor at auctor urna nunc id cursus.','Metus aliquam eleifend. Dui vivamus arcu felis bibendum ut tristique et egestas quis. Viverra tellus in hac habitasse platea. Morbi tincidunt ornare massa eget egestas. Etiam tempor orci eu lobortis elementum nibh tellus. 
Maecenas ultricies mi eget mauris pharetra. Pretium lectus quam id leo in vitae turpis massa sed. Faucibus in ornare quam viverra orci. Ullamcorper velit sed ullamcorper morbi. Imperdiet nulla malesuada pellentesque elit eget gravida cum. Nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi. Varius vel pharetra vel turpis nunc eget lorem dolor. 
Mauris vitae ultricies leo integer malesuada. Non pulvinar neque laoreet suspendisse interdum consectetur libero. Enim nec dui nunc mattis. Ultrices neque ornare aenean euismod elementum nisi.',25000,0,'2019-01-21 00:00:00','2019-07-11 00:00:00','images/dummy/25.jpg','images/dummy/26.jpg','images/dummy/27.jpg','images/dummy/28.jpg',2,10,758,0,0,132,'t'),
    ('100 pictures of Finland''s exceptional landscapes','Square Media is guiding us through a visit of Finland''s exceptional landscapes.
If you never been to Finland this project will give you an amazing prospective of the country with its authentic style.

Our team of experienced and passionate photographers will lead you to this discovery. Known touristic sites will be included in the portfolio but our team will also capture new unknown sites that will probably make Finland your next holiday target.

At the completion of this project, the album of 100 pictures will be available on the official website of Square Media Corporation. 
As soon as the funds are raised, our investors are welcome to give suggestions on themes or particular sites they want to include in the portfolio.

Each of them will also have free access to use our portfolio pictures for private and commercial use.',46425,0,'2019-02-12 00:00:00','2019-06-08 00:00:00','images/dummy/21.jpg','images/dummy/22.jpg','images/dummy/23.jpeg','images/dummy/24.jpg',3,9,845,0,0,230,'t'),
    ('Digital platform for drafting and building profesionnal templates','Acme Corporation will help everybody make their own templates in the simplest way. This free online editor will make it a matter of minutes without the need to install anything. 
A panoply tools will be available for everyonve to build a template illustrating their dreams. All you need will be there to create a stunning custom design ready for download. It''s quick, easy and fun !

Our investors will have free registered accounts for an unlimited amount of time. They will also have premium features making their work more professionnal.',15482,0,'2019-03-26 00:00:00','2019-07-23 00:00:00','images/dummy/17.png','images/dummy/18.jpg','images/dummy/19.png','images/dummy/20.jpg',4,2,1542,489,125,875,'t'),
    ('Technology project Lorem ipsum dolor sit amet, consectetur adipiscing elit. ','Technology project 
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer a porta quam. Nunc nec sagittis orci. Fusce sit amet convallis enim. Nulla facilisi. In accumsan tristique ligula non luctus. Pellentesque eget tincidunt ipsum, vitae condimentum est. Quisque volutpat nunc orci, non mollis arcu mattis eget. Sed a nisl ullamcorper, tristique ante ac, laoreet odio. 

Nullam semper pretium tortor, in malesuada ex pharetra in. Praesent turpis justo, tincidunt sed quam eget, fermentum aliquet neque. Vestibulum hendrerit felis eget urna porta ultrices. Donec congue est vitae mi ultrices semper. Integer quis magna sed neque lacinia imperdiet ornare quis justo. Praesent tincidunt felis quis tempus auctor. Nulla turpis eros, suscipit sed porttitor sed, congue ut felis.

Sed sagittis, est ut posuere pellentesque, tellus tellus aliquam nisi, at pharetra purus tellus ut odio. Curabitur vitae dolor nibh. Sed vehicula urna a elit blandit ornare. Ut fringilla tellus sem, eget posuere risus rhoncus eu. Etiam lectus orci, sollicitudin ut interdum ut, lacinia a massa. Integer consectetur sit amet eros non mollis. Sed congue convallis justo sit amet luctus.

 Quisque condimentum, sapien eu lacinia consectetur, magna odio sollicitudin purus, vitae placerat est augue id lacus. Proin at urna ipsum. Fusce tincidunt turpis diam, nec pulvinar sem tincidunt non. Ut egestas, ligula nec condimentum vestibulum, ligula augue bibendum ante, ac tempus tortor sem rhoncus sapien. Vivamus finibus vel massa non ornare. Fusce ac dolor a tellus interdum ultricies eu a dui. Pellentesque imperdiet vitae mauris ut condimentum.
',27896,0,'2018-12-10 00:00:00','2019-05-31 00:00:00','images/dummy/11.jpg','images/dummy/12.jpg','images/dummy/12.jpg','images/dummy/13.jpg',5,11,5841,1526,154,1452,'t'),
    ('Photography project Nunc nec sagittis orci. Fusce sit amet convallis enim. ','Nullam semper pretium tortor, in malesuada ex pharetra in. Praesent turpis justo, tincidunt sed quam eget, fermentum aliquet neque. Vestibulum hendrerit felis eget urna porta ultrices. Donec congue est vitae mi ultrices semper. Integer quis magna sed neque lacinia imperdiet ornare quis justo. Praesent tincidunt felis quis tempus auctor. Nulla turpis eros, suscipit sed porttitor sed, congue ut felis.

Sed sagittis, est ut posuere pellentesque, tellus tellus aliquam nisi, at pharetra purus tellus ut odio. Curabitur vitae dolor nibh. Sed vehicula urna a elit blandit ornare. Ut fringilla tellus sem, eget posuere risus rhoncus eu. Etiam lectus orci, sollicitudin ut interdum ut, lacinia a massa. Integer consectetur sit amet eros non mollis. Sed congue convallis justo sit amet luctus.

 Quisque condimentum, sapien eu lacinia consectetur, magna odio sollicitudin purus, vitae placerat est augue id lacus. Proin at urna ipsum. Fusce tincidunt turpis diam, nec pulvinar sem tincidunt non. Ut egestas, ligula nec condimentum vestibulum, ligula augue bibendum ante, ac tempus tortor sem rhoncus sapien. Vivamus finibus vel massa non ornare. Fusce ac dolor a tellus interdum ultricies eu a dui. Pellentesque imperdiet vitae mauris ut condimentum.',26547,0,'2019-01-11 00:00:00','2019-07-03 00:00:00','images/dummy/8.jpg','images/dummy/9.jpg','images/dummy/10.jpg','images/dummy/14.jpg',6,9,8222,3125,254,1698,'t'),
    ('health project Nullam semper pretium tortor, in malesuada ex pharetra in. ','Quisque condimentum, sapien eu lacinia consectetur, magna odio sollicitudin purus, vitae placerat est ugue id lacus. Proin at urna ipsum. Fusce tincidunt turpis diam, nec pulvinar sem tincidunt non. Ut egestas, ligula nec condimentum vestibulum, ligula augue bibendum ante, ac tempus tortor sem rhoncus sapien. Vivamus finibus vel massa non ornare. Fusce ac dolor a tellus interdum ultricies eu a dui. Pellentesque imperdiet vitae mauris ut condimentum.
Praesent turpis justo, tincidunt sed quam eget, fermentum aliquet neque. Vestibulum hendrerit felis eget urna porta ultrices. Donec congue est vitae mi ultrices semper. Integer quis magna sed neque lacinia imperdiet ornare quis justo. Praesent tincidunt felis quis tempus auctor. Nulla turpis eros, suscipit sed porttitor sed, congue ut felis.

Sed sagittis, est ut posuere pellentesque, tellus tellus aliquam nisi, at pharetra purus tellus ut odio. Curabitur vitae dolor nibh. Sed vehicula urna a elit blandit ornare. Ut fringilla tellus sem, eget posuere risus rhoncus eu. Etiam lectus orci, sollicitudin ut interdum ut, lacinia a massa. Integer consectetur sit amet eros non mollis. Sed congue convallis justo sit amet luctus.',8945,0,'2019-01-22 00:00:00','2019-06-12 00:00:00','images/dummy/4.jpg','images/dummy/5.jpg','images/dummy/6.jpg','images/dummy/7.jpg',7,5,544,0,0,250,'t'),
    ('technology project  sapien eu lacinia consectetur, magna odio sollicitudin purus, vitae placerat est ugue id lacus.','Ut ac pulvinar orci. Cras dui dolor, posuere sit amet elementum sed, ullamcorper eu tellus. Donec sollicitudin ullamcorper lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce ipsum turpis, vestibulum vel quam eget, malesuada consequat magna. Aliquam cursus nulla dolor. Nullam pretium aliquam quam, et consectetur felis.

Duis pellentesque lorem sed consequat malesuada. Vestibulum nec libero consectetur, semper tortor at, tempus lectus. Nulla metus leo, ullamcorper sed ullamcorper ut, auctor quis neque. Fusce nisi ex, scelerisque at ante vitae, posuere semper magna. Aliquam fringilla lacinia leo, sed pellentesque lorem dapibus at. Donec lorem nisl, feugiat ut gravida quis, semper quis nibh. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce et nisi eleifend, aliquam ligula at, tempus ligula. Nunc rutrum vel est porta facilisis. Mauris egestas mattis suscipit. Vestibulum odio sapien, sodales et dui ut, commodo tristique magna. Sed eget ante et eros hendrerit ornare in id orci. Nulla accumsan porttitor dui, vel mattis mauris.',13548,0,'2019-02-14 00:00:00','2019-07-20 00:00:00','images/dummy/29.jpg','images/dummy/1.jpeg','images/dummy/2.jpg','images/dummy/3.jpg',8,11,3875,752,111,298,'t'),
    ('Health homeopathy project orci. Cras dui dolor, posuere sit amet elementum sed','Ullamcorper eu tellus. Donec sollicitudin ullamcorper lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce ipsum turpis, vestibulum vel quam eget, malesuada consequat magna. Aliquam cursus nulla dolor. Nullam pretium aliquam quam, et consectetur felis.

Nulla metus leo, ullamcorper sed ullamcorper ut, auctor quis neque. Fusce nisi ex, scelerisque at ante vitae, posuere semper magna. Aliquam fringilla lacinia leo, sed pellentesque lorem dapibus at. Donec lorem nisl, feugiat ut gravida quis, semper quis nibh. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce et nisi eleifend, aliquam ligula at, tempus ligula. Nunc rutrum vel est porta facilisis. Mauris egestas mattis suscipit. Vestibulum odio sapien, sodales et dui ut, c.',4856,0,'2019-02-17 00:00:00','2019-07-10 00:00:00','images/dummy/30.jpg','images/dummy/31.jpg','images/dummy/32.jpg','images/dummy/33.jpg',9,5,460,0,0,103,'t'),
    ('Fashion project Adipiscing bibendum est ultricies integer quis auctor elit. ','Vel quam elementum pulvinar etiam non quam. Risus feugiat in ante metus dictum. Neque egestas congue quisque egestas diam in. Fermentum dui faucibus in ornare quam viverra orci. Dui nunc mattis enim ut tellus elementum sagittis vitae et. Sed felis eget velit aliquet sagittis id consectetur. Sit amet risus nullam eget felis eget nunc lobortis. Quisque id diam vel quam elementum pulvinar etiam non quam. Odio facilisis mauris sit amet massa vitae. Non quam lacus suspendisse faucibus interdum posuere lorem.

Curabitur gravida arcu ac tortor dignissim convallis. Aenean et tortor at risus viverra adipiscing at in. Ultricies mi eget mauris pharetra et ultrices neque ornare. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Pulvinar etiam non quam lacus suspendisse. Ornare suspendisse sed nisi lacus sed viverra. Non curabitur gravida arcu ac tortor dignissim convallis. Malesuada fames ac turpis egestas. Cursus risus at ultrices mi. Curabitur gravida arcu ac tortor. Dictum non consectetur a erat nam at lectus urna. Ut tristique et egestas quis.',11479,0,'2019-01-03 00:00:00','2019-08-03 00:00:00','images/dummy/34.jpg','images/dummy/35.jpg','images/dummy/36.jpg','images/dummy/37.jpg',10,4,4782,521,250,358,'t'),
    ('Events Sagittis nisl rhoncus mattis rhoncus urna neque. ','Tempus egestas sed sed risus pretium quam vulputate. Diam maecenas ultricies mi eget. Placerat in egestas erat imperdiet sed. Odio ut enim blandit volutpat maecenas volutpat. Blandit turpis cursus in hac. Consequat semper viverra nam libero justo laoreet. Egestas congue quisque egestas diam in arcu cursus euismod. Sapien faucibus et molestie ac feugiat sed lectus.
Elementum tempus egestas sed sed risus pretium quam vulputate. Nibh nisl condimentum id venenatis a condimentum vitae sapien. Velit dignissim sodales ut eu sem integer vitae justo eget. Sit amet nulla facilisi morbi tempus iaculis urna. Dignissim sodales ut eu sem integer vitae justo eget. 

Eget duis at tellus at urna condimentum mattis pellentesque id. Sit amet volutpat consequat mauris nunc congue nisi vitae suscipit. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Viverra accumsan in nisl nisi scelerisque eu. Nam libero justo laoreet sit amet.',24896,0,'2019-03-20 00:00:00','2019-08-12 00:00:00','images/dummy/38.jpg','images/dummy/39.jpg','images/dummy/40.jpg','images/dummy/41.jpg',11,3,3589,842,149,520,'t'),
    ('Marketing Diam maecenas ultricies mi eget. Placerat in egestas erat imperdiet sed. ','Odio ut enim blandit volutpat maecenas volutpat. Blandit turpis cursus in hac. Consequat semper viverra nam libero justo laoreet. Egestas congue quisque egestas diam in arcu cursus euismod. Sapien faucibus et molestie ac feugiat sed lectus.
Sed sed risus pretium quam vulputate. Nibh nisl condimentum id venenatis a condimentum vitae sapien. Velit dignissim sodales ut eu sem integer vitae justo eget. Sit amet nulla facilisi morbi tempus iaculis urna. Dignissim sodales ut eu sem integer vitae justo eget. 
At tellus at urna condimentum mattis pellentesque id. Sit amet volutpat consequat mauris nunc congue nisi vitae suscipit. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Viverra accumsan in nisl nisi scelerisque eu. Nam libero justo laoreet sit amet.',33698,0,'2019-03-16 00:00:00','2019-07-22 00:00:00','images/dummy/42.jpg','images/dummy/43.jpg','images/dummy/44.jpg','images/dummy/45.jpg',12,6,8547,3547,359,1890,'t');
