Insert into users(userfname, userlname, username, useremail, userpassword, userphoto, userdob, useraddress, usercountry, companyname, companylogo, companydescription, nbshareordinary, sharevalueordinary, descordinary, additionalordinary, nbsharepreferencial, sharevaluepreferencial, descpreferencial, additionalpreferencial, nbsharenonvoting, sharevaluenonvoting, descnonvoting, additionalnonvoting, nbshareredeemable, sharevalueredeemable, descredeemable, additionalredeemable, userassets, isadmin, "validatedUser") VALUES
    ('super','admin','admin','admin@cfunding.com','Testons123','images/avatar-admin.png','1993-12-29 00:00:00','25 Rue Louis','Mauritius','Equity Funders','images/equity-logo.png',NULL,0,0,NULL,NULL,0,0,NULL,NULL,0,0,NULL,NULL,0,0,NULL,NULL,0,'t','t'),
    ('Cecilia','Reulet','cecilia_reulet','ceciliaR@test.com','Testons123','images/avatar-women-1.jpg','1985-03-25 00:00:00','145 Ave St Lo','Maldives','Cube Corp','images/company-cubeCorp.PNG','Nothing says, a nonspecific international company serving the needs of consumers through service and synergy like Cube Corps. According to the official Time Journal, the mission statement of Cube Corp is be the leading enterprise. Sounds about right.',1852,0.057,NULL,NULL,0,0,NULL,NULL,0,0,NULL,NULL,250,0.041,NULL,NULL,250.658,'f','t'),
    ('Ally','Johnson','ally_johnson','allyJ@test.com','Testons123','images/avatar-women-2.png','1987-10-06 00:00:00','256 Baker Street','Finland','Square Media','images/company-squareMedia.PNG','Square Media says intense, passionate, insistent; it’s a contemporary built artistic platform, where new talents can show their work and get feedback on how they perform from people all over the world. ',4300,0.078,NULL,NULL,0,0,NULL,NULL,0,0,NULL,NULL,854,0.053,NULL,NULL,870.125,'f','t'),
    ('Mireya','Dagenhart','mireya_dagenhart','mireya@test.com','Testons123','images/avatar-women-3.png','1990-07-22 00:00:00','2149  Hilltop Haven Drive','Germany','Acme Corporation','images/company-acmeCorporation.PNG','When it comes to findings good inspiration for the design of your project Acme could be your perfect companion. Our rich platform of design templates and templates ideas can give you the ideal look for your business portfolio.',6240,0.24,NULL,NULL,1246,0.30,NULL,NULL,502,0.26,NULL,NULL,1347,0.18,NULL,NULL,5600.498,'f','t'),
    ('Lynna','Fazenbaker','lynna_fazenbaker','lynna@test.com','Testons123','images/avatar-women-4.png','1986-11-14 00:00:00','4 Abbe Ave','Poland','Initech','images/company-initech.PNG','"ini" – innovation, "tech" – technology reveals itself a 2 years experiences startup proving its worth in the new technologies development world. Composed of a young team of inspired professionals Initech is one of the most popular Technology service providers.',10587,0.16,NULL,NULL,3874,0.19,NULL,NULL,825,0.18,NULL,NULL,2568,0.10,NULL,NULL,8541.256,'f','t'),
    ('Lauren','Legrand','lauren_legrand','laurenl@test.com','Testons123','images/avatar-women-5.jpg','1989-03-05 00:00:00','856 Mall Ave','France','Snapshot Ltd','images/company-snapshot.PNG','For photography lovers Snapshot is the platform to take inspiration. Its large collection of images and themes makes it the first place to find exceptional photos.',13458,0.17,NULL,NULL,6571,0.28,NULL,NULL,812,0.21,NULL,NULL,2247,0.12,NULL,NULL,15245.250,'f','t'),
    ('Carine','Simons','carine_simons','carineS@test.com','Testons123','images/avatar-women-6.png','1989-05-15 00:00:00','122 Rue Dupere','Greece','Soylent Corp','images/company-soylentCorp.PNG','Soylent Corp inspires a real-life brand name of nutritional supplement and sensation. But the genius often lies in their believability. Now you can buy yourself an actual bag of Soylent and pray that, unlike fictional supplement "Soylent Green" from the film of the same name.',2300,0.09,NULL,NULL,0,0,NULL,NULL,0,0,NULL,NULL,1246,0.065,NULL,NULL,630.584,'f','t'),
    ('Henry','Baker','henry_brasher','henryB@example.com','Testons123','images/avatar-men-1.png','1989-10-12 00:00:00','2718  Tenmile Road','United States','LexCorp','images/company-lexCorp.PNG','If you are a New-Tech lover, LexCorp can help you realize the Robot of your dreams. Combining expert knowledge in robotics, mechanics and electrical technologies LexCorps has been for 3 years a reference in the robotics world.',7841,0.15,NULL,NULL,2543,0.22,NULL,NULL,423,0.16,NULL,NULL,1426,0.154,NULL,NULL,6314.512,'f','t'),
    ('Thomas','Brown','thomas_brown','thomasB@test.com','Testons123','images/avatar-men-2.png','1988-06-12 00:00:00','78 Alford Street','United Kingdom','Osato Pharma Corporation','images/company-osatoPharmaCorp.PNG','In the Homeopathic Universe, there’s Osato Bio-Pharma Corporation. This bio-engineering pharmaceutical company and laboratory is equal parts science and natural products. Its slogan perfectly sums up the bio-organic value Osato has. "Our business is life itself." We love helping and providing good-quality natural supplements to our clients…',1250,0.035,NULL,NULL,0,0,NULL,NULL,0,0,NULL,NULL,351,0.021,NULL,NULL,250.458,'f','t'),
    ('Jude','Craig','jude_craig','judeC@test.com','Testons123','images/avatar-men-3.jpg','1986-08-22 00:00:00','3236  Ersel Street','United States','NoLunt Ltd','images/company-noLunt.PNG','Fashion is emerging so rapidly from eveningwear to innerwear. Are you a fashionpreneur searching for a tailor-fit company that best describes your budget-friendly apparels and other accessories that fit for all seasons? NoLunt is made for you...',6895,0.142,NULL,NULL,2875,0.201,NULL,NULL,524,0.168,NULL,NULL,1241,0.124,NULL,NULL,4225.689,'f','t'),
    ('Steven','Ivancev','steven_ivancev','steven@test.com','Testons123','images/avatar-men-4.png','1985-12-01 00:00:00','8157 West Marconi Drive ','Hungary','Hiolty Events','images/company-hiolty.jpg','Hiolty Events is your ideal partner for organising events. From 
corporate events, dinner galas, fundraisers, weddings, grand openings, conferences and also private events, Hioly has it covered for you.
We love details! And our goal is to realize the best celebration you need. From a 1000 person dinner gala to a small intimate private party or meeting, Hiolty Events has experienced it all.  ',7921,0.181,NULL,NULL,2489,0.26,NULL,NULL,481,0.175,NULL,NULL,1856,0.16,NULL,NULL,5489.367,'f','t'),
    ('Andrew','Johnson','andrew_johnson','andrew@test.com','Testons123','images/avatar-men-5.png','1987-02-16 00:00:00','118 Orange Ave. ','Australia','Drew Enterprises','images/company-drew.PNG','Promoting new commercial ideas is never easy to work. Drew Enterprises specialized in advertisement helps growing and professional businesses to market their projects in the best possible way.',12450,0.22,NULL,NULL,5873,0.41,NULL,NULL,846,0.35,NULL,NULL,3412,0.117,NULL,NULL,12400.578,'f','t');
